"""initial migration

Revision ID: d6ec17f885e1
Revises: 
Create Date: 2024-08-23 20:45:50.007975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ec17f885e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coefficient', sa.NUMERIC(precision=20, scale=2), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_table('bets',
    sa.Column('bet_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('bet_sum', sa.NUMERIC(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('bet_id')
    )
    op.create_index(op.f('ix_bets_bet_id'), 'bets', ['bet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_bet_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
